### PR TITLE
patch to put updated

### PR DESCRIPTION
**Pull request by Elizabethcodes44**
https://trello.com/c/DjZUcRBm/199-apiclient-update-patch-to-put

### CODE REVIEW

**Comment by Luca-Terrazzan** [comment]
@Elizabethcodes44 can you add a reference to the Trello ticket this is related to?

**Comment by Luca-Terrazzan** [comment]
@Elizabethcodes44  Are these routes already existing and updated on the server side? I can't seem to find them on the main branch. What would happen if we merge this and the APIs aren't ready yet?

**Comment by PeachyOmnivore** [comment]
@Luca-Terrazzan These routes are being created in another branch by another student on server side.

**Comment by Luca-Terrazzan** [comment]
> @Luca-Terrazzan These routes are being created in another branch by another student on server side.

Got it, do you have a strategy for dealing with the backend release first? Or are you good with having the frontend updated anyways?

**Review by Luca-Terrazzan — APPROVED** [review]

**Comment by PeachyOmnivore** [comment]
Waited for backend. It is now merged.

**Pull request merged**
